language: perl
addons:
  apt:
    packages:
      - libsnmp-dev
branches:
  only:
    - /^2\.\d{6}$/
    - 'master'
install: true
script: |
  perl Build.PL && \
  ./Build && \
  PERL_MM_USE_DEFAULT=1 ./Build installdeps --cpan_client 'cpanm --quiet --notest' && \
  ./Build test --test_files xt/
