# This is the main configuration file for Netdisco web and daemon apps
# all the settings in this file will be loaded at Dancer's startup.

# Web app env-related settings should go to environments/$env.yml

# application's name
appname: "Netdisco"

# The default web layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# web sessions stored on disk
session: "YAML"

# HTTP port to listen on
port: 5000

# logging format
logger_format: '[%P] %L @%D> %m'

# web output template settings
template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'
    PRE_CHOMP: 1

# Netdisco stuff (can be overidden in the environment .yml)

web_plugins:
  - Inventory
  - Report::DuplexMismatch
  - AdminTask::PseudoDevice
  - AdminTask::Topology
  - AdminTask::JobQueue
  - Search::Device
  - Search::Node
  - Search::VLAN
  - Search::Port
  - Device::Details
  - Device::Ports
#  - Device::Modules
  - Device::Neighbors
  - Device::Addresses

discover_no: []
discover_only: []

snmpver: 2
snmpretries: 2
snmptimeout: 1000000

# If unset, Netdisco uses "NETDISCO_HOME/netdisco-mibs", assuming you're
# using the netdisco-deploy script to download MIBs there.  Otherwise, set
# this, for example:
#
# mibhome: /usr/share/netdisco/mibs

# If unset, loads all MIBs in the mibhome directory.
# mibdirs:
#   - cisco
#   - rfc
#   - net-snmp

community: ['public']
community_rw: ['private']

# rights control for Interactive jobs
vlanctl: 1
portctl_uplinks: 0
portctl_nophones: 1
portctl_vlans: 1

ignore_interfaces:
  - 'EOBC'
  - 'unrouted VLAN'
  - 'StackPort'
  - 'Control Plane Interface'
  - 'SPAN (S|R)P Interface'
  - 'StackSub'
  - 'netflow'
  - 'Vlan\d+-mpls layer'
  - 'BRI\S+-Bearer Channel'
  - 'BRI\S+-Physical'
  - 'BRI\S+-Signalling'
  - 'Embedded-Service-Engine\d+\/\d+'
  - 'Virtual-Template\d+'
  - 'Virtual-Access\d+'
  - '(E|T)\d \d\/\d\/\d'
  - 'Vlan1'

workers:
  # how many daemon processes for this node
  interactives: 2
  pollers: 2
  # sleep time between polls of the database job queue
  sleep_time: 5

# what housekeeping tasks should this node *schedule*
# (it only does them if workers->pollers is non-zero)
#housekeeping:
#  discoverall:
#    when: '0 9 * * *'
#  arpwalk:
#    when:
#      min: 30
#  macwalk:
#    when:
#      hour: '*/2'
